### ISSUE TITLE
Reference existing values in subparser

### ISSUE THREAD

**Issue by fhubik** [rhos-infra/InfraRed#164]
Can we achieve somehow:

```
../ospd.spec
- title: Product
    options:
    product-version:
          type: Value
          help: The product version
          required: yes
          choices: ["7", "8"]
...
   images-version:
          type: Value
          default: <VALUE_OF product-version>
          help: Specifies the import image url. Required only when images task is 'build'
```

This way we don't have to specify multiple parameters like
--product-version=8
--images-version=8
...=8
...
Other way I can think of is connect references in playbooks with existing yaml parameter (product.version), this would mean also we can not specify separate "version" values both e.g. for product and/or images.

**Comment by yfried-redhat** [comment]
I suggest to have core-version optional and use ansible/Jinja "default()" filter in playbook:
```yaml
product:
    version: "{{ installer.product.version }}"
    core:
        version: "{{ installer.product.core.version | default(installer.product.version) }}"
```
