### ISSUE TITLE
Wait_for (SSH) is not testing SSH sanity properly

### ISSUE THREAD

**Issue by fhubik** [rhos-infra/InfraRed#216]
For example following code testing SSH sanity might not work, because it cares only about SSH service ability to respond, not that SSH is really able to execude desired commands right it this moment. Tasks closely following this test and expecting working and sane SSH access, might fail, because of the delay between SSH_is_up and SSH_is_able_to_execute_commands, might be dozen seconds (not considering it might never happen!).
# (at the EOF of playbooks/provisioner/virsh/main.yml playbook is this)

```
- name: Check SSH connection to newly created VMs
  hosts: all:!localhost
  gather_facts: no
  tasks:
      - name: wait for hosts to be reachable
        wait_for:
            port: 22
            host: "{{ ansible_ssh_host }}"
            delay: 10
        delegate_to: virthost
# 
- name: This next play/task here might FAIL as SSH might not be able to execute commands yet!
  hosts: all:!localhost
  ...
```
